sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: DT9o6Te0b0iCyBSi2X6dhRq6mc88K6rdQkBJ4M82Bc+hftHWNrod4iOfBWGVhV0uBbAfWSD/6hnXcdw9MphYH0XhjBlEzZsKQg7cdZfq/rq6fcuxPtMn+CUYiTVtaNKUWKO4hUCVBwhHMUIR6Q2B+uA9yv/zdVzi2ocyVg4s/cWPUdWz4SKlzZ21c6XiiL6Kdg3GlCKouLkb3+g7uD48YrIy3uZrgEXcLisnL/rUgDVKnTK9jwtMIwCOn2S1hLtcsuIF1nPBIDl09C1zyCZdRjwJbnnL+i2axtrXjU/apy+Loj9xGb763YUZqjMDZUvNxVaYc3AvW0OjA8rwD33P+LrG1Xb4c9YjHcgTz+sM8L1bqRJgs066EY5gkVjKhYjTCC26jO4D2IVLAy4DqVxIwNGCHeveV1FbjJzmLqpZluyC+Ry+LoTD3XskW0sQg5T8HHfGPK5YERrCuqXxmawbCpHxJ5w753wiC4sfzwiMZJRYtFDPMMhYDhZrTVGjs+qztD+lQJqSAyUrIAWSR4noJYxKRLX9DBynRoeRrn32WM7C/aGk2SCiVVvNM9rhHSib0z1ZWcEBmxC/HxrkeLj0Bl1EuVtn7KdBkbibVtMAoCA4GyqEKuDVCtlB+lf54K2wArE+gYbyfTBmZLCABtAkHBihWE7Eq8GLE+yxdqecilU=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Earth-as-Modified-by-Human-Action_6019
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy